[2024-09-02T00:56:04.140+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clickhouse_to_sqlite.data_from_clickhouse manual__2024-09-02T00:56:01.823511+00:00 [queued]>
[2024-09-02T00:56:04.143+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clickhouse_to_sqlite.data_from_clickhouse manual__2024-09-02T00:56:01.823511+00:00 [queued]>
[2024-09-02T00:56:04.143+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-09-02T00:56:04.150+0000] {taskinstance.py:2192} INFO - Executing <Task(_PythonDecoratedOperator): data_from_clickhouse> on 2024-09-02 00:56:01.823511+00:00
[2024-09-02T00:56:04.156+0000] {standard_task_runner.py:60} INFO - Started process 199 to run task
[2024-09-02T00:56:04.158+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'clickhouse_to_sqlite', 'data_from_clickhouse', 'manual__2024-09-02T00:56:01.823511+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/clickhouse_to_sqlite.py', '--cfg-path', '/tmp/tmpgpslpbo6']
[2024-09-02T00:56:04.165+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask data_from_clickhouse
[2024-09-02T00:56:04.202+0000] {task_command.py:423} INFO - Running <TaskInstance: clickhouse_to_sqlite.data_from_clickhouse manual__2024-09-02T00:56:01.823511+00:00 [running]> on host 49db2d0c7729
[2024-09-02T00:56:04.241+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='clickhouse_to_sqlite' AIRFLOW_CTX_TASK_ID='data_from_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-09-02T00:56:01.823511+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-02T00:56:01.823511+00:00'
[2024-09-02T00:56:06.836+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 242, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/clickhouse_to_sqlite.py", line 33, in data_from_clickhouse
    data = client.execute(query)
AttributeError: 'HttpClient' object has no attribute 'execute'
[2024-09-02T00:56:06.863+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=clickhouse_to_sqlite, task_id=data_from_clickhouse, execution_date=20240902T005601, start_date=20240902T005604, end_date=20240902T005606
[2024-09-02T00:56:06.886+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 21 for task data_from_clickhouse ('HttpClient' object has no attribute 'execute'; 199)
[2024-09-02T00:56:06.926+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-09-02T00:56:06.949+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
